# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-05 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizer.Option')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizer.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='options',
            field=models.ManyToManyField(related_name='topics', through='categorizer.TopicOption', to='categorizer.Option'),
        ),
        migrations.AddField(
            model_name='optionranking',
            name='topicoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='categorizer.TopicOption'),
        ),
        migrations.AddField(
            model_name='optionranking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.ManyToManyField(to='categorizer.OptionRanking'),
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='categorizer.OptionRanking'),
        ),
        migrations.AlterUniqueTogether(
            name='topicoption',
            unique_together=set([('option', 'topic')]),
        ),
        migrations.AlterUniqueTogether(
            name='optionranking',
            unique_together=set([('topicoption', 'user')]),
        ),
    ]
