# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='topics',
            field=models.ManyToManyField(related_name='options', to='categorizer.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('category', 'label')]),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('category', 'label')]),
        ),
    ]
